<?php

class tresHautDeGamme extends Item {
    public string $quality;

    public function __construct(int $id,string $name, int $price,  string $imageURL, int $weight, int $stock,string $quality){
        parent::__construct( $id, $name, $price,   $imageURL,  $weight,  $stock);
        $this->quality=$quality;
    }

    public function displayItem()
    {
        parent::displayItem(); // TODO: Change the autogenerated stub
    }
}